[versions]
clikt = "5.0.3"
cloud-command = "2.0.0"
jline = "3.30.5"
jserialcomm = "2.11.4"
junit = "5.13.4"
kotlin = "2.2.20"
kotlin-logging = "7.0.13"
kotlinx-coroutines = "1.10.2"
mordant = "3.0.2"
log4j = "2.25.1"
slf4j = "1.7.36"

# Plugins
blossom = "2.1.0"
dokka = "2.1.0-Beta"
indra = "3.2.0"
ktlint = "13.1.0"
shadow = "9.1.0"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

# Libraries
jserialcomm = { module = "com.fazecast:jSerialComm", version.ref = "jserialcomm" }

# Logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

# CLI
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud-command" }
cloud-kotlin = { module = "org.incendo:cloud-kotlin-extensions", version.ref = "cloud-command" }
jline = { module = "org.jline:jline", version.ref = "jline" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }

# Tests
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

# Plugins used in build src
blossom = { module = "net.kyori:blossom", version.ref = "blossom" }
dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-git = { module = "net.kyori:indra-git", version.ref = "indra" }
kotlin-jvm-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

[bundles]
kotlinx-coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-jdk8"]
build-plugins = [
    "blossom",
    "dokka-plugin",
    "indra-common",
    "indra-git",
    "kotlin-jvm-plugin",
    "ktlint-plugin",
]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dooka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
